#+title: M.Tech Projects
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />
#+OPTIONS: html-style:nil toc:nil title:nil num:nil timestamp:nil

#+begin_export html
<ul class="sidebar" id="mySideNav">
  <a href="javascript:void(0);" class="icon" onclick="myFunction()"><b>MENU</b></a>
  <a href="../index.html">Home</a>
  <a href="../research-topics/_index.html">Research Topics</a>
  <a href="../publications.html">Publications</a>
  <a class="active" href="./_index.html">Projects</a>
  <a href="../bio.html">Bio</a>
</ul>
#+end_export

#+INCLUDE: ../logo.org

* Image Segmentation using Watershed Transform
- M.Tech 1st Semester
- Team Size: 2
- Software Used: MATLAB and Python
Implemented immersion simulations on grayscale images to segment different regions by using watershed transform.

* Image mosaic using homography estimation
- M.Tech 2nd Semester
- Software used: MATLAB
Stiched five images taken of a subject from five different viewpoints to create a mosaic. Implemented SIFT matching from ~vlfeat.org~ and used homography estimation using normalization of scales to morph images to stich them in a mosaic.

* Finding rotation and translation direction using two images
- M.Tech 2nd Semester
- Software used: MATLAB
Computed the rotation and translation direction between two images using the Hartley normalization for the eight point algorithm. Matching points were computed using SIFT and outliers removed using RANSAC.
