#+title: Kanishak | Home
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./style.css" />
#+OPTIONS: html-style:nil toc:nil title:nil num:nil timestamp:nil

#+begin_export html
<ul class="sidebar" id="mySideNav">
  <a href="javascript:void(0);" class="icon" onclick="myFunction()"><b>MENU</b></a>
  <a class="active" href="./index.html">Home</a>
  <a href="./research-topics/index.html">Research Topics</a>
  <a href="./publications.html">Publications</a>
  <a href="./projects/index.html">Projects</a>
  <a href="./bio.html">Bio</a>
</ul>
#+end_export

#+INCLUDE: ./logo.org

* About Me
I am PhD graduate from the Indian Institute of Science, Bangalore, with a research interest in wireless distributed systems. During my PhD, I have worked on distributed machine learning systems, broadcast networks for information retrieval and delivery, and wireless cache-aided networks, focusing on privacy and security.

After acquiring AIR 10 in GATE (EC) 2018, I joined IISc for an M.Tech in signal processing and upgraded to a PhD after one year. I have hands-on experience in image processing and computer vision projects. I also have a strong background in coding and information theory.
-----
** Achievements
- Received Prime Minister's Research Fellowship (PMRF) from January 2020 to July 2023
- Achieved All India Rank 10 in GATE EC 2018
- Achieved All India Rank 20 in Junior Mathematical Olympiad 2011
-----
** Education
| Qualification   | Institute         | Specialization                  | Graduated |
|-----------------+-------------------+---------------------------------+-----------|
| *PhD*           | IISc Bangalore    | Communications                  | Nov 2023  |
| *M.Tech*        | IISc Bangalore    | Signal Processing               | Jul 2023  |
| *B.Tech*        | JNGEC Sundernagar | Electronics and Communications  | Jul 2017  |
| *10+2*          | KV Mandi          | Non Medical and Medical Science | Mar 2013  |
| *Matriculation* | KV Mandi          | Science                         | Mar 2011  |
