#+title: M.Tech Projects
#+weight: 4
#+lead: Technical projects that I've worked on during M.Tech
#+comments:
#+authorbox:
#+pager:
#+mathjax: true
#+sidebar:
#+widgets[]: search recent taglist

- Image segmentation using watershed transform
- Image mosaic using homography estimation
- Computer vision: Finding rotation and translation direction using two images
# more
* Image Segmentation using Watershed Transform
- M.Tech 1st Semester
- Team Size: 2
- Software Used: MATLAB and Python
Implemented immersion simulations on grayscale images to segment different regions by using watershed transform.

* Image mosaic using homography estimation
- M.Tech 2nd Semester
- Software used: MATLAB
Stiched five images taken of a subject from five different viewpoints to create a mosaic. Implemented SIFT matching from ~vlfeat.org~ and used homography estimation using normalization of scales to morph images to stich them in a mosaic.

* Finding rotation and translation direction using two images
- M.Tech 2nd Semester
- Software used: MATLAB
Computed the rotation and translation direction between two images using the Hartley normalization for the eight point algorithm. Matching points were computed using SIFT and outliers removed using RANSAC.
