#+title: Coded Caching
#+description: Private Information Delivery
#+weight: 13
#+tags[]: research
#+thumbnail: coded-caching.png
#+comments:
#+authorbox:
#+pager: true
#+sidebar: right
#+widgets[]: search recent taglist

The high temporal variability of network traffic results in communication systems that are congested during peak-traffic times and underutilized during off-peak times. One approach to reduce peak traffic is to take advantage of memories distributed across the network (at end users, routers, …) to duplicate content. This duplication of content, called content placement or caching, is performed during off-peak hours when network resources are abundant. During peak hours, when network resources are scarce, user requests can then be served exploiting these caches to reduce network congestion.

# more

* Introduction
The coded caching problem was introduced by M. A. Maddah-Ali and U. Niesen, in "Fundamental limits of caching," 2013 IEEE International Symposium on Information Theory, 2013, pp. 1077-1081, doi: 10.1109/ISIT.2013.6620392. This problem consists of a server connected through a shared, error-free link to \(K\) users. The server stores \(N\) files \(W_1 , \cdots W_N\) each of size \(F\) bits. User \(k , \forall k \in [K]\) has an isolated cache memory \(Z_k\) of size \(MF\) bits for some real number \(M \in [0:N]\).

The system operates in two phases.
1. *Placement Phase*: This phase corresponds to the off-peak hours, when the network traffic is low. In this phase, the users cache are filled from some arbitrary functions of the files.
2. *Delivery Phase*: In this phase, user \(k , \forall k \in [K]\) request a file \(W_{d_k}\) from the server. Every user request a file independently. After receiving the users' requests, the server proceeds by transmitting a signal of size \(RF\) bits over the shared link. Using the content \(Z_k\) of its cache and the signal received over the shared link, each user \(k\) aims to reconstruct its requested file \(W_{d_k}\).

** Multi-access Coded caching
In multi-access coded caching setup, users don't have access to dedicated caches. There are \(C\) cache nodes and each user can access \(L \leq C\) cache nodes. In placement phase, these cache nodes are filled with some arbitrary function of the files. Then in delivery phase, users request their desired files from the server. Server performs coded transmissions of size \(RF\) bits and users should be able to decode their desired files from these transmissions and the content stored in the caches they are accessing.

* Our Contribution
We considered the problem of cache-aided [[{{% ref "/research-topics/PIR.org" %}}][private information retrieval]]. In this setup, there are \(B\) non-colluding servers storing \(N\) files. We propose a Private Information Retrieval scheme in which \(K\) users aided with \(C\) Multi-Access cache nodes privately retrieve data from distributed servers. We considered several multi-access setups with multiple non-colluding servers with all the messages replicated across the servers. Each server is connected to all the users via error-free broadcast links.

** Publications
- Kanishak Vaidya and B. Sundar Rajan, ``Cache-Aided Multi-Access Multi-User Private Information Retrieval,'' in Wi-Opt CCDWN 2022, Turin, Italy, 19 -- 23 September 2022.
- Kanishak Vaidya and B. Sundar Rajan, ``Multi-Access Cache-Aided Multi-User Private Information Retrieval,'' arXiv:2201.11481, 9 Feb 2022.
