#+title: Private Information Retrieval
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />
#+OPTIONS: html-style:nil toc:nil title:nil num:nil timestamp:nil

#+begin_export html
<ul class="sidebar" id="mySideNav">
  <a href="javascript:void(0);" class="icon" onclick="myFunction()"><b>MENU</b></a>
  <a href="../index.html">Home</a>
  <a class="active" href="../research-topics/index.html">Research Topics</a>
  <a href="../publications.html">Publications</a>
  <a href="../projects/index.html">Projects</a>
  <a href="../bio.html">Bio</a>
</ul>
#+end_export

#+INCLUDE: ../logo.org

* Introduction
The problem of Private Information Retrieval (PIR), first described by Chor et. al. in "Private information retrieval," Proceedings of IEEE 36th Annual Foundations of Computer Science, 1995, pp. 41-50, doi: 10.1109/SFCS.1995.492461., deals with privately retrieving data from a set of distributed servers. A user wishes to retrieve one file among a set of files stored across the servers. But the servers should not know the identity of the desired file. A PIR scheme that minimizes the download cost for the user is described by H. Sun and S. A. Jafar, in ``The Capacity of Private Information Retrieval,'' in IEEE Transactions on Information Theory, vol. 63, no. 7, pp. 4075-4088, July 2017, doi: 10.1109/TIT.2017.2689028. After that, the PIR problem is solved for various other settings.

In Private Information Retrieval (PIR) there is one user and a set of \(N\) files \(W_1 , \cdots , W_N\) replicated across \(S\) non-colluding servers. The user wants to retrieve one out of \(N\) files, say file \(W_{D}\), but does not want servers to know the identity of the file. In other words, the user wants to hide the index \(D\) from the servers. In order to retrieve this desired file privately, the user generates \(S\) queries and sends query \(Q_s^{D}\) to server \(s\). After receiving their respective queries, servers construct answers which are a function of the query they received and the files they are storing. After receiving answers from all the servers, the user should be able to decode the desired file.

* Our Contribution
We considered the PIR problem in conjunction with another content delivery problem known as the [[{{% ref "/research-topics/coded-caching.org" %}}][coded caching]] problem. In this setup, there are \(B\) non-colluding servers storing \(N\) files. We propose a Private Information Retrieval scheme in which \(K\) users aided with \(C\) Multi-Access cache nodes privately retrieve data from distributed servers. We considered several multi-access setups with multiple non-colluding servers with all the messages replicated across the servers. Each server is connected to all the users via error-free broadcast links.

** Publications
- Kanishak Vaidya and B. Sundar Rajan, ``Cache-Aided Multi-Access Multi-User Private Information Retrieval,'' in Wi-Opt CCDWN 2022, Turin, Italy, 19 -- 23 September 2022.
- Kanishak Vaidya and B. Sundar Rajan, ``Multi-Access Cache-Aided Multi-User Private Information Retrieval,'' arXiv:2201.11481, 9 Feb 2022.
